<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Все производители");?>
<?
	//include module
	\Bitrix\Main\Loader::includeModule("dw.deluxe");

	//vars
	$catalogIblockId = null;
	$arPriceCodes = array();

	//get template settings
	$arTemplateSettings = DwSettings::getInstance()->getCurrentSettings();
	if(!empty($arTemplateSettings)){
		$catalogIblockId = $arTemplateSettings["TEMPLATE_PRODUCT_IBLOCK_ID"];
		$arPriceCodes = explode(", ", $arTemplateSettings["TEMPLATE_PRICE_CODES"]);
	}
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"brands", 
	array(
		"IBLOCK_TYPE" => "info",
		"IBLOCK_ID" => "1",
		"NEWS_COUNT" => "50",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "Y",
		"USE_REVIEW" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "TIMESTAMP_X",
		"SORT_ORDER2" => "DESC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"USE_SHARE" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "",
		"LIST_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "TAGS",
			5 => "SORT",
			6 => "PREVIEW_TEXT",
			7 => "PREVIEW_PICTURE",
			8 => "DETAIL_TEXT",
			9 => "DETAIL_PICTURE",
			10 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "OFFERS",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_ACTIVE_DATE_FORMAT" => "",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => "visual",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Производители",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"TAGS_CLOUD_ELEMENTS" => "150",
		"PERIOD_NEW_TAGS" => "",
		"DISPLAY_AS_RATING" => "rating",
		"FONT_MAX" => "50",
		"FONT_MIN" => "10",
		"COLOR_NEW" => "3E74E6",
		"COLOR_OLD" => "C0C0C0",
		"TAGS_CLOUD_WIDTH" => "100%",
		"SEF_FOLDER" => "/brands/",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "brands",
		"SET_LAST_MODIFIED" => "N",
		"DETAIL_SET_CANONICAL_URL" => "Y",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"PRODUCT_IBLOCK_TYPE" => "catalog",
		"PRODUCT_IBLOCK_ID" => "15",
		"PRODUCT_FILTER_NAME" => "arrFilter",
		"PRODUCT_PROPERTY_CODE" => array(
			0 => "OFFERS",
			1 => "ATT_BRAND",
			2 => "CML2_ARTICLE",
			3 => "MORE_PROPERTIES",
			4 => "COLOR",
			5 => "ZOOM2",
			6 => "BATTERY_LIFE",
			7 => "SWITCH",
			8 => "GRAF_PROC",
			9 => "LENGTH_OF_CORD",
			10 => "DISPLAY",
			11 => "LOADING_LAUNDRY",
			12 => "FULL_HD_VIDEO_RECORD",
			13 => "INTERFACE",
			14 => "COMPRESSORS",
			15 => "Number_of_Outlets",
			16 => "MAX_RESOLUTION_VIDEO",
			17 => "MAX_BUS_FREQUENCY",
			18 => "MAX_RESOLUTION",
			19 => "FREEZER",
			20 => "POWER_SUB",
			21 => "POWER",
			22 => "HARD_DRIVE_SPACE",
			23 => "MEMORY",
			24 => "OS",
			25 => "ZOOM",
			26 => "PAPER_FEED",
			27 => "SUPPORTED_STANDARTS",
			28 => "VIDEO_FORMAT",
			29 => "SUPPORT_2SIM",
			30 => "MP3",
			31 => "ETHERNET_PORTS",
			32 => "MATRIX",
			33 => "CAMERA",
			34 => "PHOTOSENSITIVITY",
			35 => "DEFROST",
			36 => "SPEED_WIFI",
			37 => "SPIN_SPEED",
			38 => "PRINT_SPEED",
			39 => "SOCKET",
			40 => "IMAGE_STABILIZER",
			41 => "GSM",
			42 => "SIM",
			43 => "TYPE",
			44 => "MEMORY_CARD",
			45 => "TYPE_BODY",
			46 => "TYPE_MOUSE",
			47 => "TYPE_PRINT",
			48 => "CONNECTION",
			49 => "TYPE_OF_CONTROL",
			50 => "TYPE_DISPLAY",
			51 => "TYPE2",
			52 => "REFRESH_RATE",
			53 => "RANGE",
			54 => "AMOUNT_MEMORY",
			55 => "MEMORY_CAPACITY",
			56 => "VIDEO_BRAND",
			57 => "DIAGONAL",
			58 => "RESOLUTION",
			59 => "TOUCH",
			60 => "CORES",
			61 => "LINE_PROC",
			62 => "PROCESSOR",
			63 => "CLOCK_SPEED",
			64 => "TYPE_PROCESSOR",
			65 => "PROCESSOR_SPEED",
			66 => "HARD_DRIVE",
			67 => "HARD_DRIVE_TYPE",
			68 => "Number_of_memory_slots",
			69 => "MAXIMUM_MEMORY_FREQUENCY",
			70 => "TYPE_MEMORY",
			71 => "BLUETOOTH",
			72 => "FM",
			73 => "GPS",
			74 => "HDMI",
			75 => "SMART_TV",
			76 => "USB",
			77 => "WIFI",
			78 => "FLASH",
			79 => "ROTARY_DISPLAY",
			80 => "SUPPORT_3D",
			81 => "SUPPORT_3G",
			82 => "WITH_COOLER",
			83 => "FINGERPRINT",
			84 => "TOTAL_OUTPUT_POWER",
			85 => "HTML",
			86 => "VID_ZASTECHKI",
			87 => "VID_SUMKI",
			88 => "PROFILE",
			89 => "VYSOTA_RUCHEK",
			90 => "GAS_CONTROL",
			91 => "WARRANTY",
			92 => "GRILL",
			93 => "GENRE",
			94 => "OTSEKOV",
			95 => "CONVECTION",
			96 => "INTAKE_POWER",
			97 => "NAZNAZHENIE",
			98 => "BULK",
			99 => "PODKLADKA",
			100 => "SURFACE_COATING",
			101 => "brand_tyres",
			102 => "SEASONOST",
			103 => "DUST_COLLECTION",
			104 => "REF",
			105 => "DRYING",
			106 => "REMOVABLE_TOP_COVER",
			107 => "CONTROL",
			108 => "FINE_FILTER",
			109 => "FORM_FAKTOR",
			110 => "SKU_COLOR",
			111 => "MARKER_PHOTO",
			112 => "NEW",
			113 => "DELIVERY_DESC",
			114 => "SALE",
			115 => "MARKER",
			116 => "POPULAR",
			117 => "WEIGHT",
			118 => "HEIGHT",
			119 => "DEPTH",
			120 => "WIDTH",
			121 => "",
		),
		"PRODUCT_PRICE_CODE" => array(
		),
		"PRODUCT_CONVERT_CURRENCY" => "Y",
		"PRODUCT_CURRENCY_ID" => "RUB",
		"HIDE_NOT_AVAILABLE" => "N",
		"FILTER_PRICE_CODE" => array(
		),
		"HIDE_MEASURES" => "N",
		"CATEGORY_IBLOCK" => array(
		),
		"CATEGORY_CODE" => "CATEGORY",
		"CATEGORY_ITEMS_COUNT" => "5",
		"STRICT_SECTION_CHECK" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?><?$APPLICATION->IncludeComponent(
	"dresscode:slider", 
	"middle", 
	array(
		"IBLOCK_TYPE" => "slider",
		"IBLOCK_ID" => "9",
		"CACHE_TYPE" => "Y",
		"CACHE_TIME" => "3600000",
		"PICTURE_WIDTH" => "1476",
		"PICTURE_HEIGHT" => "202",
		"COMPONENT_TEMPLATE" => "middle"
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>